### ISSUE TITLE
Get Nagios alerts working on the normal Nagios cookbook

### ISSUE THREAD

**Issue by rettigs** [osuosl-cookbooks/rdiff-backup#17]
Currently, rdiff-backup Nagios alerts don't work with the normal Nagios cookbook; it relies on a custom patched version.  There needs to be a way to handle Nagios alerts without that.  It might be worth looking into chef-rewind to monkeypatch the Nagios cookbook on the fly.

**Comment by rettigs** [comment]
I just thought of an idea that could allow this to work.  The problem with using chef-rewind is that it can't modify the resources of a different node (how could it?).  However, I could create a small rdiff-backup recipe that runs on the Nagios server.  That recipe can then read the node attributes set by the ridff-backup server for the checks that need to be added and use chef-rewind to add them to the services.conf template's services attribute.

**Comment by armiller** [comment]
iirc @jordane added nagios alerts support via databags in his recent patch. Does that resolve this issue?

**Comment by rettigs** [comment]
@armiller As far as I know, we just switched to a system where all the checks have to be specified manually in data bags, which was always a possibility.  The patched Nagios version just allowed the checks to be created automatically, but since we're trying to use upstream Nagios again, we lost that functionality and I don't know that we've reimplemented it some other way yet.
