### ISSUE TITLE
Test Kitchen Tests

### ISSUE THREAD

**Issue by rettigs** [osuosl-cookbooks/rdiff-backup#5]
Databags should be added for Test Kitchen to use so we can actually test the server instead of just the trivial "is rdiff-backup installed" tests that currently exist.

Look at https://github.com/tas50/nagios/tree/master/test/integration for reference.

**Comment by rettigs** [comment]
Perhaps the tests could involve simply running all of the backup scripts at least once using a test server and test client with predetermined data and MySQL databases, then comparing the rdiff-backup directory with the known files to make sure they are there and identical.  This wouldn't catch bugs involving the cron job or diffs, but it would be a good start.

**Comment by rettigs** [comment]
Solving https://github.com/osuosl-cookbooks/rdiff-backup/issues/8 would make testing MySQL backups easier since we wouldn't need to fuss with SSH keys.

**Comment by rettigs** [comment]
It might also be a good idea to run tests using several different combinations of attributes that toggle functionality so that we get higher line/path coverage in the tests.

**Comment by rettigs** [comment]
Being resolved by https://github.com/osuosl-cookbooks/rdiff-backup/pull/13

**Comment by armiller** [comment]
A test cookbook does not exists. @jordane I believe we can consider this issues resolved with your changes?

**Comment by jordane** [comment]
Yep. This has to be tested with chef-provisioning, not test-kitchen.
