### ISSUE TITLE
Add MySQL/PostgreSQL Backup Functionality

### ISSUE THREAD

**Issue by rettigs** [osuosl-cookbooks/rdiff-backup#6]
This can be accomplished by performing dumps to local disk, running rdiff-backup on it to diff it, then deleting the dump.  However, I'm not sure if this is the best way, for the following reasons:

- Dumping to the rdiff-backup server uses a lot of network bandwidth, negating the benefits of only transferring diffs like rdiff-backup normally does.
- Dumping to either the database server or the rdiff-backup server uses a lot of disk space.  Perhaps the databases can be dumped to a transparently compressed filesystem mount so not as much buffer space is needed?

I am wondering if perhaps the database data can be copied directly from the filesystem.  Maybe we could locking the database to do an LVM snapshot and then backing up that?  Or is there another tool that would be more ideal?  It would be nice to have all backups done with the same program though, instead of having 2 or 3 different backup systems.

**Comment by armiller** [comment]
Whats the current status of backups with rdiff?

**Comment by ramereth** [comment]
Me and @jordane have a plan for mysql, but not for pg yet.

**Comment by jordane** [comment]
rdiff and mysql have nothing to do with each other though, so I'm closing this.
