### ISSUE TITLE
Don't Use SSH for Local Backups

### ISSUE THREAD

**Issue by rettigs** [osuosl-cookbooks/rdiff-backup#8]
Currently, all backups are tunneled through SSH, even when backing up local mounts.  Running rdiff-backup directly could yield a performance improvement.

**Comment by rettigs** [comment]
This needs to be implemented for MySQL jobs too now.

**Comment by armiller** [comment]
Since this issues is regarding SSH backups I am going to close this issue. We should create a new issue if we want to support local mysql backups.
